language: bash

sudo: required

services:
  - docker

env:
  global:
    - IMAGE_BASE=fnichol/rust
  matrix:
    - VERSION=nightly VARIANT= LATEST=true
    - VERSION=nightly VARIANT=slim
    - VERSION=1.15.1 VARIANT=
    - VERSION=1.15.1 VARIANT=slim
    - VERSION=1.15.1 VARIANT=musl
    - VERSION=1.15.0 VARIANT=
    - VERSION=1.15.0 VARIANT=slim
    - VERSION=1.15.0 VARIANT=musl
    - VERSION=1.14.0 VARIANT=
    - VERSION=1.14.0 VARIANT=slim
    - VERSION=1.14.0 VARIANT=musl
    - VERSION=1.13.0 VARIANT=
    - VERSION=1.13.0 VARIANT=slim
    - VERSION=1.13.0 VARIANT=musl
    - VERSION=1.12.0 VARIANT=
    - VERSION=1.12.0 VARIANT=slim
    - VERSION=1.12.0 VARIANT=musl

before_script:
  - env | sort

script:
  - sh scripts/build.sh

after_script:
  - docker images

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then sh scripts/deploy.sh; fi
