language: bash

sudo: required

services:
  - docker

env:
  global:
    - IMAGE_BASE=fnichol/rust
  matrix:
    - VERSION=nightly VARIANT= LATEST=true
    - VERSION=nightly VARIANT=slim
    - VERSION=1.4.0 VARIANT=
    - VERSION=1.4.0 VARIANT=slim
    - VERSION=1.4.0 VARIANT=musl
    - VERSION=1.3.0 VARIANT=
    - VERSION=1.3.0 VARIANT=slim
    - VERSION=1.2.0 VARIANT=
    - VERSION=1.2.0 VARIANT=slim

before_script:
  - env | sort
  - pushd "$VERSION"
  - IMAGE="${IMAGE_BASE}:$VERSION${VARIANT:+-$VARIANT}"

script:
  - docker build -t "$IMAGE" "${VARIANT:-.}"
  - if [ -n "$LATEST" ]; then docker build -t "${IMAGE_BASE}:latest" "${VARIANT:-.}"; fi

after_script:
  - popd
  - docker images

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then sh scripts/deploy.sh; fi
