language: bash

sudo: required

services:
  - docker

env:
  global:
    - IMAGE_BASE=fnichol/rust
  matrix:
    - VERSION=nightly VARIANT= LATEST=true
    - VERSION=nightly VARIANT=slim
    - VERSION=1.15.0 VARIANT=
    - VERSION=1.15.0 VARIANT=slim
    - VERSION=1.15.0 VARIANT=musl
    - VERSION=1.14.0 VARIANT=
    - VERSION=1.14.0 VARIANT=slim
    - VERSION=1.14.0 VARIANT=musl
    - VERSION=1.13.0 VARIANT=
    - VERSION=1.13.0 VARIANT=slim
    - VERSION=1.13.0 VARIANT=musl
    - VERSION=1.12.0 VARIANT=
    - VERSION=1.12.0 VARIANT=slim
    - VERSION=1.12.0 VARIANT=musl
    - VERSION=1.11.0 VARIANT=
    - VERSION=1.11.0 VARIANT=slim
    - VERSION=1.11.0 VARIANT=musl
    - VERSION=1.10.0 VARIANT=
    - VERSION=1.10.0 VARIANT=slim
    - VERSION=1.10.0 VARIANT=musl
    - VERSION=1.9.0 VARIANT=
    - VERSION=1.9.0 VARIANT=slim
    - VERSION=1.9.0 VARIANT=musl
    - VERSION=1.8.0 VARIANT=
    - VERSION=1.8.0 VARIANT=slim
    - VERSION=1.8.0 VARIANT=musl
    - VERSION=1.7.0 VARIANT=
    - VERSION=1.7.0 VARIANT=slim
    - VERSION=1.6.0 VARIANT=
    - VERSION=1.6.0 VARIANT=slim
    - VERSION=1.5.0 VARIANT=
    - VERSION=1.5.0 VARIANT=slim
    - VERSION=1.4.0 VARIANT=
    - VERSION=1.4.0 VARIANT=slim
    - VERSION=1.3.0 VARIANT=
    - VERSION=1.3.0 VARIANT=slim
    - VERSION=1.2.0 VARIANT=
    - VERSION=1.2.0 VARIANT=slim

before_script:
  - env | sort

script:
  - sh scripts/build.sh

after_script:
  - docker images

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then sh scripts/deploy.sh; fi
