language: bash

sudo: required

services:
  - docker

env:
  global:
    - IMAGE_BASE=fnichol/rust
  matrix:
    - VERSION=nightly VARIANT= LATEST=true
    - VERSION=nightly VARIANT=slim
    - VERSION=1.4.0 VARIANT=
    - VERSION=1.4.0 VARIANT=slim
    - VERSION=1.3.0 VARIANT=
    - VERSION=1.3.0 VARIANT=slim
    - VERSION=1.2.0 VARIANT=
    - VERSION=1.2.0 VARIANT=slim

before_script:
  - env | sort
  - cd "$VERSION"
  - image="${IMAGE_BASE}:$VERSION${VARIANT:+-$VARIANT}"

script:
  - docker build -t "$image" "${VARIANT:-.}"
  - if [ -n "$LATEST" ]; then docker build -t "${IMAGE_BASE}:latest" "${VARIANT:-.}"; fi

after_script:
  - docker images

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push "$image"
  - if [ -n "$LATEST" ]; then docker push "${IMAGE_BASE}:latest"; fi
  - rm -rf "$HOME/.docker"
